#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOSQL
CREATE USER n8n WITH PASSWORD '${N8N_DB_PASSWORD}';
CREATE DATABASE n8n OWNER n8n;

CREATE USER agentlab WITH PASSWORD '${AGENT_DB_PASSWORD}';
CREATE DATABASE agentlab OWNER agentlab;
EOSQL
